
services:
  web:
    container_name: navicula-dev-web
    tmpfs: /tmp
    build:
      context: web/
      dockerfile: Dockerfile.dev
    volumes:
      # Removed named volume for node_modules to use modules from image build
      - dev_nuxt:/app/.nuxt
      - dev_node_modules:/app/node_modules
      - ./web:/app
    depends_on:
      - api
    ports:
      - "3000:3000"
      
  api:
    container_name: navicula-dev-api
    tmpfs: /tmp
    build:
      context: api/
      dockerfile: Dockerfile.dev
    volumes:
      - ./config.yml:/app/config.yml
      - ./api:/app

volumes:
  dev_node_modules:
  dev_nuxt:
