
services:
  navicula:
    image: ghcr.io/odie-software/navicula:latest
    container_name: navicula
    volumes:
      - ./config.yml:/app/config.yml # Mount config.yml
      - ./users.yml:/app/users.yml   # Mount user settings
