# Generated by Django 5.2.1 on 2025-05-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplicationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, help_text="Identifier for the user (e.g., email or 'default').", max_length=255)),
                ('app_id', models.CharField(db_index=True, help_text="Identifier for the application (e.g., 'app-vikunja'). Must match an app_id in the main config.", max_length=100)),
                ('settings', models.JSONField(blank=True, default=dict, help_text="Application-specific settings for the user (e.g., {'api_key': '...'}).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Application Setting',
                'verbose_name_plural': 'User Application Settings',
                'ordering': ['user_identifier', 'app_id'],
                'unique_together': {('user_identifier', 'app_id')},
            },
        ),
    ]
