# Generated by Django 5.2.1 on 2025-05-11 20:15

import users.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplicationsetting',
            name='settings',
            field=users.fields.EncryptedJSONField(blank=True, default=dict, help_text="Application-specific settings for the user (e.g., {'api_key': '...'}), stored encrypted."),
        ),
    ]
