# .github/workflows/ci.yml

name: CI - Build and Push Docker Image

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ] # Run on pushes to the main branch
  # Optional: Run on Pull Requests to main (builds but doesn't push)
  # pull_request:
  #   branches: [ "main" ]
  # Optional: Allow manual runs from the Actions tab
  workflow_dispatch:

# Environment variables available to all jobs and steps
env:
  # CHANGE THESE: Replace with your details
  # Option 1: GitHub Container Registry (ghcr.io)
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # Format: ghcr.io/USERNAME/REPOSITORY or ghcr.io/ORG/REPOSITORY

  # Option 2: Docker Hub (Uncomment below and comment out Option 1)
  # REGISTRY: docker.io
  # IMAGE_NAME: YOUR_DOCKERHUB_USERNAME/YOUR_IMAGE_NAME # Format: docker.io/USERNAME/IMAGENAME

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    # Set permissions for the GITHUB_TOKEN for GHCR pushes.
    # Not required for Docker Hub if using a PAT.
    permissions:
      contents: read      # To checkout the code
      packages: write     # To push packages (docker images) to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out your code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred Node.js version

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # Or your preferred pnpm version
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: ./app # Run pnpm install in the app directory
        run: pnpm install --frozen-lockfile

      - name: Run Linter (ESLint)
        working-directory: ./app # Run lint in the app directory
        run: pnpm lint

      - name: Run Formatter Check (Prettier)
        working-directory: ./app # Run format check in the app directory
        run: pnpm format

      - name: Log in to the Container registry
        # This action logs in to a Docker registry
        # For GHCR, it uses the built-in GITHUB_TOKEN
        # For Docker Hub, you'll need to provide DOCKERHUB_USERNAME and a DOCKERHUB_TOKEN (Personal Access Token) as secrets
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          # --- GHCR Login ---
          username: ${{ github.actor }}       # Your GitHub username or org name
          password: ${{ secrets.GITHUB_TOKEN }} # Automatically generated token
          # --- Docker Hub Login (use these instead if using Docker Hub) ---
          # username: ${{ secrets.DOCKERHUB_USERNAME }}
          # password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        # This action extracts useful metadata like git sha, tags, etc.
        # It automatically generates appropriate tags based on the event (e.g., 'latest' for default branch push, git sha)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/odie-software/navicula
          # Example Tags:
          # - type=schedule
          # - type=ref,event=branch
          # - type=ref,event=pr
          # - type=semver,pattern={{version}}
          # - type=semver,pattern={{major}}.{{minor}}
          # - type=semver,pattern={{major}}
          # - type=sha # Adds the git short SHA as a tag

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # This action creates a BuildKit builder instance

      - name: Build and push Docker image
        # This action builds the Docker image and pushes it to the registry
        uses: docker/build-push-action@v5
        with:
          context: . # Build context is the root of the repository
          # Optional: Specify Dockerfile location if not in root:
          # file: ./path/to/your/Dockerfile
          push: ${{ github.event_name != 'pull_request' }} # Only push on 'push' events (like merging to main), not on 'pull_request'
          tags: ${{ steps.meta.outputs.tags }} # Use tags generated by the metadata action
          labels: ${{ steps.meta.outputs.labels }} # Add labels generated by the metadata action
          cache-from: type=gha # Enable build cache from GitHub Actions cache
          cache-to: type=gha,mode=max # Enable saving build cache to GitHub Actions cache
